# Generated by Django 4.0.4 on 2023-10-01 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_manager', '0002_single_picture_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_1', models.ImageField(upload_to='imgaes/gallery')),
                ('picture_2', models.ImageField(upload_to='imgaes/gallery')),
                ('picture_3', models.ImageField(blank=True, null=True, upload_to='imgaes/gallery')),
                ('picture_4', models.ImageField(blank=True, null=True, upload_to='imgaes/gallery')),
                ('picture_5', models.ImageField(blank=True, null=True, upload_to='imgaes/gallery')),
                ('picture_6', models.ImageField(blank=True, null=True, upload_to='imgaes/gallery')),
                ('picture_7', models.ImageField(blank=True, null=True, upload_to='imgaes/gallery')),
                ('picture_8', models.ImageField(blank=True, null=True, upload_to='imgaes/gallery')),
            ],
        ),
        migrations.AlterField(
            model_name='single_picture',
            name='picture',
            field=models.ImageField(upload_to='images/single_pictures'),
        ),
    ]
