# Generated by Django 4.0.4 on 2023-10-01 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_manager', '0003_picture_gallery_alter_single_picture_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture_gallery',
            name='picture_1',
        ),
        migrations.RemoveField(
            model_name='picture_gallery',
            name='picture_2',
        ),
        migrations.RemoveField(
            model_name='picture_gallery',
            name='picture_3',
        ),
        migrations.RemoveField(
            model_name='picture_gallery',
            name='picture_4',
        ),
        migrations.RemoveField(
            model_name='picture_gallery',
            name='picture_5',
        ),
        migrations.RemoveField(
            model_name='picture_gallery',
            name='picture_6',
        ),
        migrations.RemoveField(
            model_name='picture_gallery',
            name='picture_7',
        ),
        migrations.RemoveField(
            model_name='picture_gallery',
            name='picture_8',
        ),
        migrations.AddField(
            model_name='picture_gallery',
            name='gallery_name',
            field=models.CharField(default='My Gallery', max_length=100),
        ),
        migrations.CreateModel(
            name='Gallery_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_manager.picture_gallery')),
            ],
        ),
    ]
