# Generated by Django 4.0.4 on 2023-10-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_manager', '0004_remove_picture_gallery_picture_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_gallery',
            name='gallery_message',
            field=models.TextField(blank=True, default='Add a cute message if you wish to', null=True),
        ),
    ]
