# Generated by Django 4.0.4 on 2023-10-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_manager', '0005_picture_gallery_gallery_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery_Picture',
        ),
    ]
